#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=1172:00:00
#PBS -N lambdaU1.0_8inv
##PBS -V
#
#PBS -o job.out
#PBS -e job.err
#PBS -d /home/agnese/paper_vertex_structures/ED_pomerol/2_sites/U_1.0_beta_10.0/Vertex_structures/scripts

source /home/agnese/.bash_aliases

python /home/agnese/paper_vertex_structures/ED_pomerol/2_sites/U_1.0_beta_10.0/Vertex_structures/scripts/lambda_R_calc_8inv.py  > lambda_8inv.out 2> lambda_8inv.err
